version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alunos
      PGADMIN_DEFAULT_PASSWORD: alunos
  
  db:
    image: postgres:12
    # image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: estrategia
      POSTGRES_PASSWORD: alunos
  
  exporter:
    image: wrouesnel/postgres_exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:alunos@db:5432/estrategia?sslmode=disable" 
  
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  sonar:
    image: sonarprometheus
    ports:
      - 9000:9000

    
volumes:
  postgres-data:
