version: '3'

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teste
      PGADMIN_DEFAULT_PASSWORD: teste
  
  coruja-node:
    image: coruja-node:v2
    ports:
      - 3000:3000
    environment:
      PGUSER: teste
      PGHOST: db
      PGPASSWORD: teste
      PGDATABASE: teste
      PGPORT: 5432
      
volumes:
  postgres-data:
