version: '3.9'
services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql:5.7.39
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php
    ports:
      - 3306:3306
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
